# Add your custom configurations here
hide_window_decorations true
# active_border_color #00ff00
# inactive_border_color #cccccc
# wayland_titlebar_color system
wayland_titlebar_color black

# BEGIN_KITTY_THEME
# OneDark-Pro
include current-theme.conf
font_size 14
# END_KITTY_THEME

background_opacity 0.9
background_blur 1

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
#

cursor_shape beam
cursor_shape_unfocused block
cursor_beam_thickness 1.5
shell_integration enabled

window_padding_width 4
