typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# export PATH="$HOME/anaconda3/bin:$PATH"  # commented out by conda initialize

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"
# ZSH_THEME="cloud"
# ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias HotDown='cd ~/Documents/Scripting; ./Hotspot_Down.sh; cd ~'
alias HotUp='cd ~/Documents/Scripting; ./Hotspot.sh; cd ~'
alias ThemeGogh='cd ~/Documents/Scripting; ./Theme.sh; cd ~'
alias eyota='~/Documents/Scripting/ZakDam.sh'
alias ff='fastfetch'
alias Jakdam='~/Documents/Scripting/Windows.sh'
alias set-ip='~/Documents/Scripting/IP-LINK.sh'

# Directory-related commands
alias asdf='cd'
alias docs='cd ~/Documents'
alias downloads='cd ~/Downloads'
alias web='cd /var/www/html'
alias ..='cd ..'
alias main='cd ~/ZakiAdam/Zaki-Adam'
alias upi='cd ~/ZakiAdam/Zaki-Adam/UPI'
alias cdprog='main; cd Code/'
alias cdc='cdprog; cd C/'

# Pacman-related commands
alias install='sudo pacman -S'
alias uninstall='sudo pacman -Rns'
alias update='sudo pacman -Syu'
alias packages='pacman -Qen'
alias cleancache='sudo pacman -Sc'

# Utilities
alias zshconf="nvim ~/.zshrc"
alias bashconf="nvim ~/.bashrc"
alias nvconf="cd ~/.config/nvim/; nvim"
alias tmuxnf="nvim ~/.tmux.conf"
alias nv="nvim"
alias vim="nvim"
alias snv="sudo nvim"
alias clr="clear"
alias opengl="-lglfw -lOpenGL glad.c -lassimp"

# custom Clock commands
alias clock-cs="tty-clock -c -s"
alias clock-c="tty-clock -c"

# wireless Link auto set
alias Linkwlan0="sudo ip link set wlan0 down; sudo ip link set wlan0 up"
alias Linkwlan1="sudo ip link set wlan1 down; sudo ip link set wlan1 up"

# Daily Reminder Haha
alias rmd="~/Documents/Scripting/Queue.sh; echo Use remind for yourself!"
alias zenrmd="clear; rmd;"
alias sche="~/Documents/Scripting/schedule.sh; test"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/readam/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/readam/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/readam/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/readam/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export API_KEY="AIzaSyCM7wLY-8nkQUGoLcS5hisbYBP_ZfWkDGk"
export EDITOR="nvim"

export JAVA_HOME='/usr/lib/jvm/java-11-openjdk'
export PATH=$JAVA_HOME/bin:$PATH
export HADOOP_HOME=~/Hadoop/hadoop-3.3.6/
export PATH=$PATH:$HADOOP_HOME/bin
export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
export HIVE_HOME=~/Hadoop/apache-hive-4.0.1-bin
export PATH=$PATH:$HIVE_HOME/bin

# >>> Powerlevel10k instant prompt <<<
# The lines between these markers are managed by Powerlevel10k. Manual edits will be lost.
[[ ! -r ~/.p10k.zsh ]] || source ~/.p10k.zsh
# <<< Powerlevel10k instant prompt <<<

# Reminder for My Assignemnt
# ~/Documents/Scripting/Queue.sh
# echo "Use  remind for yourself!"
