return {
  -- {
  --   "stevearc/oil.nvim",
  --   ---@module 'oil'
  --   ---@type oil.SetupOpts
  --   opts = {
  --     view_options = {
  --       -- Show files and directories that start with "."
  --       show_hidden = true,
  --     },
  --     float = {
  --       -- Padding around the floating window
  --       padding = 2,
  --       max_width = 90,
  --       max_height = 0,
  --       -- border = "rounded",
  --       win_options = {
  --         winblend = 0,
  --       },
  --     },
  --     -- Optional dependencies
  --     dependencies = { { "echasnovski/mini.icons", opts = {} } },
  --     -- dependencies = { "nvim-tree/nvim-web-devicons" }, -- use if prefer nvim-web-devicons
  --   },
  -- },
}
